### PR TITLE
Remove dependency on AbstractPlugin

### PR DESCRIPTION
**Pull request by linawolf**
As it will be @internal with TYPO3 v12

I used your extension as example to demonstrate how you can migrate away from the abstract plugin.

### CODE REVIEW

**Comment by ghermens** [comment]
Thanks for saving me the work ... ;-)

**Comment by seirerman** [comment]
I get an error after upgrading to version 1.1.0 on TYPO3 10.4.32:
`Cannot access protected property Amazing\GhRandomcontent\Plugin\RandomContent::$cObj`

image

Downgrading to 1.0 helped, for now.

**Comment by seirerman** [comment]
I guess composer still thinks that 1.1.0 is compatible with TYPO3 10.4.
Version 1.1.1 fixed that, apparently.

**Comment by ghermens** [comment]
I just removed the 1.1.0 tag / release from Github and Packagist. Composer should choose the correct version now ...

Btw, please always open a new issue, do not hijack existing discussions. This problem was not caused by Lina's patch.

**Comment by seirerman** [comment]
Sure, will do next time. And thanks!

**Pull request merged**
